### ISSUE TITLE
A very encouraging work!

### ISSUE THREAD

**Issue by zhongpeixiang** [natashamjaques/neural_chat#1]
This "_Approximating Interactive Human Evaluation with Self-Play for Open-Domain Dialog Systems_" is a very encouraging work in the field of open-domain dialog system. I'm very happy to try your metric. I have a few questions here:

- What's the weight of each individual metric in computing the final metric?
- How did you collect the Reddit data mentioned in the paper? I'm aware of [pushshift API](https://github.com/pushshift/api) and [pushshift directory contents](http://files.pushshift.io/reddit/comments/). However, I don't know exactly how to extract Reddit comments and process them into conversations for a specific subreddit, e.g., /r/CasualConversation.

Really appreciate your hard work :)

Thanks,
Peixiang

**Comment by asmadotgh** [comment]
Hi Peixiang, Thank you for your questions.

More information can be found in the appendix of our [paper](https://arxiv.org/pdf/1906.09308.pdf):

**Re hybrid metric:** 
Appendix 7.2 provides information about weight of individual metrics and their stability across training folds. Here are the raw values with 90% confidence intervals:
```
Sentiment -U=0.608 ± 0.018
Sentiment Transition -U=-1.176 ± 0.172
Sentiment Min-Max -U=0.059 ± 0.013
Laughter -U=0.171 ± 0.015
Sentiment Coher. -U/B=0.866 ± 0.077
Semantic Coher. -U/B=-0.146 ± 0.022
Average Word Coher. -U/B=2.201 ± 0.165
Extrema Word Coher. -U/B=-2.588 ± 0.137
Greedy Word Coher. -U/B=0.244 ± 0.159
Question Score -B=-0.036 ± 0.040
#Word -U=-0.084 ± 0.171
Intercept=2.245 ± 0.037
```

**Re reddit dataset:**
Appendix 7.5 provides details about scraping reddit dataset, downloadable from [here](https://affect.media.mit.edu/neural_chat/datasets). We used submission IDs from the [1.7B Reddit comments dataset](https://bigquery.cloud.google.com/dataset/fh-bigquery:reddit_comments) and then used [PRAW](https://praw.readthedocs.io/en/latest/?source=post_page) to scrape the main submissions.

**Comment by zhongpeixiang** [comment]
@asmadotgh Thank you very much for the detailed weight info and reddit dataset collection method. 

Thanks,
Peixiang
